#############################################################################
# Makefile for building: DoorLock
# Generated by qmake (3.1) (Qt 5.11.3)
# Project:  DoorLock.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile DoorLock.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -pthread -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../temp/opencv4 -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtWidgets -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = DoorLock1.0.0
DISTDIR = /home/pi/DoorLock/.tmp/DoorLock1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lwiringPi -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_features2d -lopencv_objdetect -lopencv_videoio -pthread -lQt5Widgets -lQt5Gui -lQt5Core -lGLESv2 -lpthread -latomic 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Controller.cpp \
		Inputs.cpp \
		lcdScreen.cpp \
		main.cpp \
		Outputs.cpp \
		ComputerVision.cpp 
OBJECTS       = Controller.o \
		Inputs.o \
		lcdScreen.o \
		main.o \
		Outputs.o \
		ComputerVision.o
DIST          = /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/linux.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/qconfig.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_post.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resources.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/moc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/uic.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/yacc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/lex.prf \
		DoorLock.pro Controller.h \
		Inputs.h \
		lcdScreen.h \
		Outputs.h \
		ComputerVision.h Controller.cpp \
		Inputs.cpp \
		lcdScreen.cpp \
		main.cpp \
		Outputs.cpp \
		ComputerVision.cpp
QMAKE_TARGET  = DoorLock
DESTDIR       = 
TARGET        = DoorLock


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DoorLock.pro /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/linux.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/qconfig.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_post.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resources.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/moc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/uic.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/yacc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/lex.prf \
		DoorLock.pro \
		/usr/lib/arm-linux-gnueabihf/libQt5Widgets.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5Gui.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5Core.prl
	$(QMAKE) -o Makefile DoorLock.pro
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/linux.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/sanitize.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-base.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/qconfig.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_config.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/toolchain.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_pre.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_post.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/warn_on.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resources.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/moc.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/uic.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/file_copies.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exceptions.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/yacc.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/lex.prf:
DoorLock.pro:
/usr/lib/arm-linux-gnueabihf/libQt5Widgets.prl:
/usr/lib/arm-linux-gnueabihf/libQt5Gui.prl:
/usr/lib/arm-linux-gnueabihf/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile DoorLock.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Controller.h Inputs.h lcdScreen.h Outputs.h ComputerVision.h $(DISTDIR)/
	$(COPY_FILE) --parents Controller.cpp Inputs.cpp lcdScreen.cpp main.cpp Outputs.cpp ComputerVision.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -pthread -std=c++11 -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

Controller.o: Controller.cpp Controller.h \
		Inputs.h \
		Outputs.h \
		lcdScreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Controller.o Controller.cpp

Inputs.o: Inputs.cpp Inputs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Inputs.o Inputs.cpp

lcdScreen.o: lcdScreen.cpp lcdScreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lcdScreen.o lcdScreen.cpp

main.o: main.cpp Controller.h \
		Inputs.h \
		Outputs.h \
		lcdScreen.h \
		ComputerVision.h \
		../temp/opencv4/opencv2/opencv.hpp \
		../temp/opencv4/opencv2/opencv_modules.hpp \
		../temp/opencv4/opencv2/core.hpp \
		../temp/opencv4/opencv2/core/cvdef.h \
		../temp/opencv4/opencv2/core/hal/interface.h \
		../temp/opencv4/opencv2/core/cv_cpu_dispatch.h \
		../temp/opencv4/opencv2/core/cv_cpu_helper.h \
		../temp/opencv4/opencv2/core/fast_math.hpp \
		../temp/opencv4/opencv2/core/version.hpp \
		../temp/opencv4/opencv2/core/base.hpp \
		../temp/opencv4/opencv2/core/cvstd.hpp \
		../temp/opencv4/opencv2/core/cvstd_wrapper.hpp \
		../temp/opencv4/opencv2/core/neon_utils.hpp \
		../temp/opencv4/opencv2/core/vsx_utils.hpp \
		../temp/opencv4/opencv2/core/check.hpp \
		../temp/opencv4/opencv2/core/traits.hpp \
		../temp/opencv4/opencv2/core/matx.hpp \
		../temp/opencv4/opencv2/core/saturate.hpp \
		../temp/opencv4/opencv2/core/types.hpp \
		../temp/opencv4/opencv2/core/mat.hpp \
		../temp/opencv4/opencv2/core/bufferpool.hpp \
		../temp/opencv4/opencv2/core/mat.inl.hpp \
		../temp/opencv4/opencv2/core/persistence.hpp \
		../temp/opencv4/opencv2/core/operations.hpp \
		../temp/opencv4/opencv2/core/cvstd.inl.hpp \
		../temp/opencv4/opencv2/core/utility.hpp \
		../temp/opencv4/opencv2/core/optim.hpp \
		../temp/opencv4/opencv2/core/ovx.hpp \
		../temp/opencv4/opencv2/calib3d.hpp \
		../temp/opencv4/opencv2/features2d.hpp \
		../temp/opencv4/opencv2/flann/miniflann.hpp \
		../temp/opencv4/opencv2/flann/defines.h \
		../temp/opencv4/opencv2/flann/config.h \
		../temp/opencv4/opencv2/core/affine.hpp \
		../temp/opencv4/opencv2/dnn.hpp \
		../temp/opencv4/opencv2/dnn/dnn.hpp \
		../temp/opencv4/opencv2/dnn/version.hpp \
		../temp/opencv4/opencv2/dnn/dict.hpp \
		../temp/opencv4/opencv2/dnn/layer.hpp \
		../temp/opencv4/opencv2/dnn/dnn.inl.hpp \
		../temp/opencv4/opencv2/dnn/utils/inference_engine.hpp \
		../temp/opencv4/opencv2/flann.hpp \
		../temp/opencv4/opencv2/flann/flann_base.hpp \
		../temp/opencv4/opencv2/flann/general.h \
		../temp/opencv4/opencv2/flann/matrix.h \
		../temp/opencv4/opencv2/flann/params.h \
		../temp/opencv4/opencv2/flann/any.h \
		../temp/opencv4/opencv2/flann/saving.h \
		../temp/opencv4/opencv2/flann/nn_index.h \
		../temp/opencv4/opencv2/flann/result_set.h \
		../temp/opencv4/opencv2/flann/all_indices.h \
		../temp/opencv4/opencv2/flann/kdtree_index.h \
		../temp/opencv4/opencv2/flann/dynamic_bitset.h \
		../temp/opencv4/opencv2/flann/dist.h \
		../temp/opencv4/opencv2/flann/heap.h \
		../temp/opencv4/opencv2/flann/allocator.h \
		../temp/opencv4/opencv2/flann/random.h \
		../temp/opencv4/opencv2/flann/kdtree_single_index.h \
		../temp/opencv4/opencv2/flann/kmeans_index.h \
		../temp/opencv4/opencv2/flann/logger.h \
		../temp/opencv4/opencv2/flann/composite_index.h \
		../temp/opencv4/opencv2/flann/linear_index.h \
		../temp/opencv4/opencv2/flann/hierarchical_clustering_index.h \
		../temp/opencv4/opencv2/flann/lsh_index.h \
		../temp/opencv4/opencv2/flann/lsh_table.h \
		../temp/opencv4/opencv2/flann/autotuned_index.h \
		../temp/opencv4/opencv2/flann/ground_truth.h \
		../temp/opencv4/opencv2/flann/index_testing.h \
		../temp/opencv4/opencv2/flann/timer.h \
		../temp/opencv4/opencv2/flann/sampling.h \
		../temp/opencv4/opencv2/highgui.hpp \
		../temp/opencv4/opencv2/imgcodecs.hpp \
		../temp/opencv4/opencv2/videoio.hpp \
		../temp/opencv4/opencv2/imgproc.hpp \
		../temp/opencv4/opencv2/ml.hpp \
		../temp/opencv4/opencv2/ml/ml.inl.hpp \
		../temp/opencv4/opencv2/objdetect.hpp \
		../temp/opencv4/opencv2/objdetect/detection_based_tracker.hpp \
		../temp/opencv4/opencv2/photo.hpp \
		../temp/opencv4/opencv2/shape.hpp \
		../temp/opencv4/opencv2/shape/emdL1.hpp \
		../temp/opencv4/opencv2/shape/shape_transformer.hpp \
		../temp/opencv4/opencv2/shape/hist_cost.hpp \
		../temp/opencv4/opencv2/shape/shape_distance.hpp \
		../temp/opencv4/opencv2/stitching.hpp \
		../temp/opencv4/opencv2/stitching/warpers.hpp \
		../temp/opencv4/opencv2/stitching/detail/warpers.hpp \
		../temp/opencv4/opencv2/core/cuda.hpp \
		../temp/opencv4/opencv2/core/cuda_types.hpp \
		../temp/opencv4/opencv2/core/cuda.inl.hpp \
		../temp/opencv4/opencv2/stitching/detail/warpers_inl.hpp \
		../temp/opencv4/opencv2/stitching/detail/matchers.hpp \
		../temp/opencv4/opencv2/stitching/detail/motion_estimators.hpp \
		../temp/opencv4/opencv2/stitching/detail/util.hpp \
		../temp/opencv4/opencv2/stitching/detail/util_inl.hpp \
		../temp/opencv4/opencv2/stitching/detail/camera.hpp \
		../temp/opencv4/opencv2/stitching/detail/exposure_compensate.hpp \
		../temp/opencv4/opencv2/stitching/detail/seam_finders.hpp \
		../temp/opencv4/opencv2/stitching/detail/blenders.hpp \
		../temp/opencv4/opencv2/superres.hpp \
		../temp/opencv4/opencv2/superres/optical_flow.hpp \
		../temp/opencv4/opencv2/video.hpp \
		../temp/opencv4/opencv2/video/tracking.hpp \
		../temp/opencv4/opencv2/video/background_segm.hpp \
		../temp/opencv4/opencv2/videostab.hpp \
		../temp/opencv4/opencv2/videostab/stabilizer.hpp \
		../temp/opencv4/opencv2/videostab/global_motion.hpp \
		../temp/opencv4/opencv2/videostab/optical_flow.hpp \
		../temp/opencv4/opencv2/videostab/motion_core.hpp \
		../temp/opencv4/opencv2/videostab/outlier_rejection.hpp \
		../temp/opencv4/opencv2/videostab/motion_stabilizing.hpp \
		../temp/opencv4/opencv2/videostab/frame_source.hpp \
		../temp/opencv4/opencv2/videostab/log.hpp \
		../temp/opencv4/opencv2/videostab/inpainting.hpp \
		../temp/opencv4/opencv2/videostab/fast_marching.hpp \
		../temp/opencv4/opencv2/videostab/fast_marching_inl.hpp \
		../temp/opencv4/opencv2/videostab/deblurring.hpp \
		../temp/opencv4/opencv2/videostab/wobble_suppression.hpp \
		../temp/opencv4/opencv2/videostab/ring_buffer.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Outputs.o: Outputs.cpp Outputs.h \
		lcdScreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Outputs.o Outputs.cpp

ComputerVision.o: ComputerVision.cpp ComputerVision.h \
		../temp/opencv4/opencv2/opencv.hpp \
		../temp/opencv4/opencv2/opencv_modules.hpp \
		../temp/opencv4/opencv2/core.hpp \
		../temp/opencv4/opencv2/core/cvdef.h \
		../temp/opencv4/opencv2/core/hal/interface.h \
		../temp/opencv4/opencv2/core/cv_cpu_dispatch.h \
		../temp/opencv4/opencv2/core/cv_cpu_helper.h \
		../temp/opencv4/opencv2/core/fast_math.hpp \
		../temp/opencv4/opencv2/core/version.hpp \
		../temp/opencv4/opencv2/core/base.hpp \
		../temp/opencv4/opencv2/core/cvstd.hpp \
		../temp/opencv4/opencv2/core/cvstd_wrapper.hpp \
		../temp/opencv4/opencv2/core/neon_utils.hpp \
		../temp/opencv4/opencv2/core/vsx_utils.hpp \
		../temp/opencv4/opencv2/core/check.hpp \
		../temp/opencv4/opencv2/core/traits.hpp \
		../temp/opencv4/opencv2/core/matx.hpp \
		../temp/opencv4/opencv2/core/saturate.hpp \
		../temp/opencv4/opencv2/core/types.hpp \
		../temp/opencv4/opencv2/core/mat.hpp \
		../temp/opencv4/opencv2/core/bufferpool.hpp \
		../temp/opencv4/opencv2/core/mat.inl.hpp \
		../temp/opencv4/opencv2/core/persistence.hpp \
		../temp/opencv4/opencv2/core/operations.hpp \
		../temp/opencv4/opencv2/core/cvstd.inl.hpp \
		../temp/opencv4/opencv2/core/utility.hpp \
		../temp/opencv4/opencv2/core/optim.hpp \
		../temp/opencv4/opencv2/core/ovx.hpp \
		../temp/opencv4/opencv2/calib3d.hpp \
		../temp/opencv4/opencv2/features2d.hpp \
		../temp/opencv4/opencv2/flann/miniflann.hpp \
		../temp/opencv4/opencv2/flann/defines.h \
		../temp/opencv4/opencv2/flann/config.h \
		../temp/opencv4/opencv2/core/affine.hpp \
		../temp/opencv4/opencv2/dnn.hpp \
		../temp/opencv4/opencv2/dnn/dnn.hpp \
		../temp/opencv4/opencv2/dnn/version.hpp \
		../temp/opencv4/opencv2/dnn/dict.hpp \
		../temp/opencv4/opencv2/dnn/layer.hpp \
		../temp/opencv4/opencv2/dnn/dnn.inl.hpp \
		../temp/opencv4/opencv2/dnn/utils/inference_engine.hpp \
		../temp/opencv4/opencv2/flann.hpp \
		../temp/opencv4/opencv2/flann/flann_base.hpp \
		../temp/opencv4/opencv2/flann/general.h \
		../temp/opencv4/opencv2/flann/matrix.h \
		../temp/opencv4/opencv2/flann/params.h \
		../temp/opencv4/opencv2/flann/any.h \
		../temp/opencv4/opencv2/flann/saving.h \
		../temp/opencv4/opencv2/flann/nn_index.h \
		../temp/opencv4/opencv2/flann/result_set.h \
		../temp/opencv4/opencv2/flann/all_indices.h \
		../temp/opencv4/opencv2/flann/kdtree_index.h \
		../temp/opencv4/opencv2/flann/dynamic_bitset.h \
		../temp/opencv4/opencv2/flann/dist.h \
		../temp/opencv4/opencv2/flann/heap.h \
		../temp/opencv4/opencv2/flann/allocator.h \
		../temp/opencv4/opencv2/flann/random.h \
		../temp/opencv4/opencv2/flann/kdtree_single_index.h \
		../temp/opencv4/opencv2/flann/kmeans_index.h \
		../temp/opencv4/opencv2/flann/logger.h \
		../temp/opencv4/opencv2/flann/composite_index.h \
		../temp/opencv4/opencv2/flann/linear_index.h \
		../temp/opencv4/opencv2/flann/hierarchical_clustering_index.h \
		../temp/opencv4/opencv2/flann/lsh_index.h \
		../temp/opencv4/opencv2/flann/lsh_table.h \
		../temp/opencv4/opencv2/flann/autotuned_index.h \
		../temp/opencv4/opencv2/flann/ground_truth.h \
		../temp/opencv4/opencv2/flann/index_testing.h \
		../temp/opencv4/opencv2/flann/timer.h \
		../temp/opencv4/opencv2/flann/sampling.h \
		../temp/opencv4/opencv2/highgui.hpp \
		../temp/opencv4/opencv2/imgcodecs.hpp \
		../temp/opencv4/opencv2/videoio.hpp \
		../temp/opencv4/opencv2/imgproc.hpp \
		../temp/opencv4/opencv2/ml.hpp \
		../temp/opencv4/opencv2/ml/ml.inl.hpp \
		../temp/opencv4/opencv2/objdetect.hpp \
		../temp/opencv4/opencv2/objdetect/detection_based_tracker.hpp \
		../temp/opencv4/opencv2/photo.hpp \
		../temp/opencv4/opencv2/shape.hpp \
		../temp/opencv4/opencv2/shape/emdL1.hpp \
		../temp/opencv4/opencv2/shape/shape_transformer.hpp \
		../temp/opencv4/opencv2/shape/hist_cost.hpp \
		../temp/opencv4/opencv2/shape/shape_distance.hpp \
		../temp/opencv4/opencv2/stitching.hpp \
		../temp/opencv4/opencv2/stitching/warpers.hpp \
		../temp/opencv4/opencv2/stitching/detail/warpers.hpp \
		../temp/opencv4/opencv2/core/cuda.hpp \
		../temp/opencv4/opencv2/core/cuda_types.hpp \
		../temp/opencv4/opencv2/core/cuda.inl.hpp \
		../temp/opencv4/opencv2/stitching/detail/warpers_inl.hpp \
		../temp/opencv4/opencv2/stitching/detail/matchers.hpp \
		../temp/opencv4/opencv2/stitching/detail/motion_estimators.hpp \
		../temp/opencv4/opencv2/stitching/detail/util.hpp \
		../temp/opencv4/opencv2/stitching/detail/util_inl.hpp \
		../temp/opencv4/opencv2/stitching/detail/camera.hpp \
		../temp/opencv4/opencv2/stitching/detail/exposure_compensate.hpp \
		../temp/opencv4/opencv2/stitching/detail/seam_finders.hpp \
		../temp/opencv4/opencv2/stitching/detail/blenders.hpp \
		../temp/opencv4/opencv2/superres.hpp \
		../temp/opencv4/opencv2/superres/optical_flow.hpp \
		../temp/opencv4/opencv2/video.hpp \
		../temp/opencv4/opencv2/video/tracking.hpp \
		../temp/opencv4/opencv2/video/background_segm.hpp \
		../temp/opencv4/opencv2/videostab.hpp \
		../temp/opencv4/opencv2/videostab/stabilizer.hpp \
		../temp/opencv4/opencv2/videostab/global_motion.hpp \
		../temp/opencv4/opencv2/videostab/optical_flow.hpp \
		../temp/opencv4/opencv2/videostab/motion_core.hpp \
		../temp/opencv4/opencv2/videostab/outlier_rejection.hpp \
		../temp/opencv4/opencv2/videostab/motion_stabilizing.hpp \
		../temp/opencv4/opencv2/videostab/frame_source.hpp \
		../temp/opencv4/opencv2/videostab/log.hpp \
		../temp/opencv4/opencv2/videostab/inpainting.hpp \
		../temp/opencv4/opencv2/videostab/fast_marching.hpp \
		../temp/opencv4/opencv2/videostab/fast_marching_inl.hpp \
		../temp/opencv4/opencv2/videostab/deblurring.hpp \
		../temp/opencv4/opencv2/videostab/wobble_suppression.hpp \
		../temp/opencv4/opencv2/videostab/ring_buffer.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ComputerVision.o ComputerVision.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

